### ISSUE TITLE
Missing slash in the closing tag

### ISSUE THREAD

**Issue by ahmad-511** [gitdagray/rest_api_basics#1]
Hello Dave,
In `routes/name.js` at line 26 the `<ul>` closing tag is missing the slash in front of it,

Nice tutorial by the way

**Comment by gitdagray** [comment]
Thanks Ahmad! Great catch! 😀 I'm never perfect, but I'm striving for progress 🚀

**Comment by ahmad-511** [comment]
Me too 😁

Ahmad Murey
ZAKS Developments Group © <https://zaksdg.com>
